#!/usr/bin/env bash
# Build the host-local peer CLIs used by the benchmark suites.
#
# Tracked files describe the toolchain. Everything generated by this script is
# kept under tools/bin, tools/lib, tools/src, tools/build, or tools/venv.
# Release/tag names are the only provenance checks; no checksum or digest
# machinery is used here.

set -euo pipefail

TOOLS_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
BIN_DIR="$TOOLS_DIR/bin"
LIB_DIR="$TOOLS_DIR/lib"
SOURCE_DIR="$TOOLS_DIR/src"
BUILD_DIR="$TOOLS_DIR/build"
WORK_DIR="$BUILD_DIR/work"
DOWNLOAD_DIR="$BUILD_DIR/downloads"
VENV_DIR="$TOOLS_DIR/venv"

# shellcheck source=versions.sh
source "$TOOLS_DIR/versions.sh"

JOBS="${JOBS:-$(getconf _NPROCESSORS_ONLN 2>/dev/null || echo 2)}"
KEEP_BUILD_ARTIFACTS="${KEEP_BUILD_ARTIFACTS:-0}"

case "$KEEP_BUILD_ARTIFACTS" in
    0|1) ;;
    *)
        echo "error: KEEP_BUILD_ARTIFACTS must be 0 or 1" >&2
        exit 2
        ;;
esac

mkdir -p "$BIN_DIR" "$LIB_DIR" "$SOURCE_DIR" "$WORK_DIR" "$DOWNLOAD_DIR" \
    "$BUILD_DIR"

STAGE_DIR="$(mktemp -d "$BUILD_DIR/stage.XXXXXX")"
STAGE_BIN="$STAGE_DIR/bin"
STAGE_LIB="$STAGE_DIR/lib"
mkdir -p "$STAGE_BIN" "$STAGE_LIB"

cleanup_generated() {
    rm -rf "$STAGE_DIR"

    if [[ "$KEEP_BUILD_ARTIFACTS" == 1 ]]; then
        return
    fi

    rm -rf \
        "$WORK_DIR" \
        "$BUILD_DIR/cargo-home" \
        "$BUILD_DIR/cargo-target" \
        "$BUILD_DIR/pip-cache"
    find "$BUILD_DIR" -mindepth 1 -maxdepth 1 -type d \
        \( -name 'seqkit-*' -o -name 'stage.*' \) \
        -exec rm -rf -- {} +
}
trap cleanup_generated EXIT

require_command() {
    command -v "$1" >/dev/null 2>&1 || {
        echo "error: required command not found: $1" >&2
        exit 1
    }
}

download() {
    local url="$1" output="$2" temporary
    if [[ -s "$output" ]]; then
        return 0
    fi
    echo "download: ${url##*/}"
    temporary="$(mktemp "$output.tmp.XXXXXX")"
    if ! curl -fsSL "$url" -o "$temporary"; then
        rm -f "$temporary"
        return 1
    fi
    mv "$temporary" "$output"
}

extract_archive() {
    local archive="$1" destination="$2" temporary options
    if [[ -f "$destination/.z-fasta-source-ready" ]]; then
        return 0
    fi
    if [[ -e "$destination" ]]; then
        echo "error: source directory exists but is not installer-owned: $destination" >&2
        echo "       move it aside and rerun tools/install.sh" >&2
        exit 1
    fi
    temporary="$(mktemp -d "$SOURCE_DIR/.extract.XXXXXX")"
    case "$archive" in
        *.tar.bz2) options=(-xjf) ;;
        *.tar.gz|*.tgz) options=(-xzf) ;;
        *) echo "error: unsupported archive: $archive" >&2; exit 1 ;;
    esac
    tar "${options[@]}" "$archive" -C "$temporary" --strip-components=1
    touch "$temporary/.z-fasta-source-ready"
    mv "$temporary" "$destination"
}

clone_source() {
    local url="$1" branch="$2" destination="$3" temporary
    if [[ -f "$destination/.z-fasta-source-ready" ]]; then
        return 0
    fi
    if [[ -e "$destination" ]]; then
        echo "error: source directory exists but is not installer-owned: $destination" >&2
        echo "       move it aside and rerun tools/install.sh" >&2
        exit 1
    fi
    temporary="$(mktemp -d "$SOURCE_DIR/.clone.XXXXXX")"
    git clone --depth 1 --branch "$branch" "$url" "$temporary/repository"
    mv "$temporary/repository" "$destination"
    rmdir "$temporary"
    touch "$destination/.z-fasta-source-ready"
}

prepare_worktree() {
    local source="$1" name="$2" work
    work="$(mktemp -d "$WORK_DIR/${name}.XXXXXX")"
    cp -a "$source/." "$work/"
    printf '%s\n' "$work"
}

build_samtools() {
    local hts_archive="$DOWNLOAD_DIR/htslib-$SAMTOOLS_VERSION.tar.bz2"
    local sam_archive="$DOWNLOAD_DIR/samtools-$SAMTOOLS_VERSION.tar.bz2"
    local hts_source="$SOURCE_DIR/htslib-$SAMTOOLS_VERSION"
    local sam_source="$SOURCE_DIR/samtools-$SAMTOOLS_VERSION"
    local hts_work sam_work stage_prefix

    download "https://github.com/samtools/htslib/releases/download/$SAMTOOLS_VERSION/htslib-$SAMTOOLS_VERSION.tar.bz2" "$hts_archive"
    download "https://github.com/samtools/samtools/releases/download/$SAMTOOLS_VERSION/samtools-$SAMTOOLS_VERSION.tar.bz2" "$sam_archive"
    extract_archive "$hts_archive" "$hts_source"
    extract_archive "$sam_archive" "$sam_source"
    hts_work="$(prepare_worktree "$hts_source" "htslib-$SAMTOOLS_VERSION")"
    sam_work="$(prepare_worktree "$sam_source" "samtools-$SAMTOOLS_VERSION")"
    stage_prefix="$STAGE_DIR"

    echo "build: htslib $SAMTOOLS_VERSION"
    (cd "$hts_work" && ./configure --prefix="$stage_prefix" --libdir="$STAGE_LIB")
    make -C "$hts_work" -j"$JOBS"
    make -C "$hts_work" install

    echo "build: samtools $SAMTOOLS_VERSION"
    (cd "$sam_work" && ./configure --prefix="$stage_prefix" --with-htslib="$STAGE_DIR" LDFLAGS="-L$STAGE_LIB")
    make -C "$sam_work" -j"$JOBS"
    install -m 755 "$sam_work/samtools" "$STAGE_BIN/samtools"

    require_command patchelf
    patchelf --force-rpath --set-rpath '$ORIGIN/../lib' "$STAGE_BIN/samtools"
    env LD_LIBRARY_PATH="$STAGE_LIB" "$STAGE_BIN/samtools" --version >/dev/null
}

build_bedtools() {
    local archive="$DOWNLOAD_DIR/bedtools-$BEDTOOLS_VERSION.tar.gz"
    local source="$SOURCE_DIR/bedtools2-$BEDTOOLS_VERSION"
    local work

    download "https://github.com/arq5x/bedtools2/releases/download/v$BEDTOOLS_VERSION/bedtools-$BEDTOOLS_VERSION.tar.gz" "$archive"
    extract_archive "$archive" "$source"
    work="$(prepare_worktree "$source" "bedtools-$BEDTOOLS_VERSION")"
    echo "build: bedtools $BEDTOOLS_VERSION"
    # BEDTools' included fragments hard-code obj/<name> prerequisites. Build
    # in the ignored work copy with its native obj/ and bin/ directories so
    # those paths remain contained without modifying the upstream source.
    make -C "$work" -j"$JOBS" bin/bedtools
    install -m 755 "$work/bin/bedtools" "$STAGE_BIN/bedtools"
}

build_seqkit() {
    local archive="$DOWNLOAD_DIR/seqkit-$SEQKIT_VERSION.tar.gz"
    local source="$BUILD_DIR/seqkit-$SEQKIT_VERSION"
    local binary

    if [[ ! -d "$source" ]]; then
        download "https://github.com/shenwei356/seqkit/releases/download/v$SEQKIT_VERSION/seqkit_linux_amd64.tar.gz" "$archive"
        mkdir "$source"
        tar -xzf "$archive" -C "$source"
    fi
    binary="$(find "$source" -type f -name seqkit -print -quit)"
    [[ -n "$binary" ]] || { echo "error: seqkit binary not found" >&2; exit 1; }
    install -m 755 "$binary" "$STAGE_BIN/seqkit"
}

build_seqtk() {
    local archive="$DOWNLOAD_DIR/seqtk-$SEQTK_VERSION.tar.gz"
    local source="$SOURCE_DIR/seqtk-$SEQTK_VERSION"
    local work

    download "https://github.com/lh3/seqtk/archive/refs/tags/v$SEQTK_VERSION.tar.gz" "$archive"
    extract_archive "$archive" "$source"
    work="$(prepare_worktree "$source" "seqtk-$SEQTK_VERSION")"
    echo "build: seqtk $SEQTK_DISPLAY_VERSION"
    make -C "$work"
    install -m 755 "$work/seqtk" "$STAGE_BIN/seqtk"
}

build_fastahack() {
    local source="$SOURCE_DIR/fastahack-$FASTAHACK_VERSION"
    local work

    clone_source "https://github.com/ekg/fastahack.git" "v$FASTAHACK_VERSION" "$source"
    work="$(prepare_worktree "$source" "fastahack-$FASTAHACK_VERSION")"
    echo "build: fastahack $FASTAHACK_VERSION"
    make -C "$work"
    install -m 755 "$work/fastahack" "$STAGE_BIN/fastahack"
}

build_wrapper() {
    local directory="$1" binary="$2" output="$3"
    local manifest="$TOOLS_DIR/$directory/Cargo.toml"
    local target="$BUILD_DIR/cargo-target/$directory"
    mkdir -p "$target"
    echo "build: $output"
    CARGO_HOME="$BUILD_DIR/cargo-home" cargo build --locked --release \
        --manifest-path "$manifest" --target-dir "$target"
    install -m 755 "$target/release/$binary" "$STAGE_BIN/$output"
}

install_python_tools() {
    if [[ ! -x "$VENV_DIR/bin/python" ]]; then
        python3 -m venv "$VENV_DIR"
    fi
    echo "install: pyfaidx $PYFAIDX_VERSION"
    echo "install: report packages matplotlib $MATPLOTLIB_VERSION, pandas $PANDAS_VERSION, tabulate $TABULATE_VERSION"
    PIP_CACHE_DIR="$BUILD_DIR/pip-cache" \
        "$VENV_DIR/bin/python" -m pip install --quiet --disable-pip-version-check \
        "pyfaidx==$PYFAIDX_VERSION" \
        "matplotlib==$MATPLOTLIB_VERSION" \
        "pandas==$PANDAS_VERSION" \
        "tabulate==$TABULATE_VERSION"
}

verify_stage() {
    env -u LD_LIBRARY_PATH "$STAGE_BIN/samtools" --version | grep -q "samtools $SAMTOOLS_VERSION"
    "$STAGE_BIN/bedtools" --version | grep -q "v$BEDTOOLS_VERSION"
    "$STAGE_BIN/seqkit" version | grep -q "v$SEQKIT_VERSION"
    { "$STAGE_BIN/seqtk" 2>&1 || true; } | grep -q "Version: $SEQTK_DISPLAY_VERSION"
    "$STAGE_BIN/noodles" --version | grep -q "$NOODLES_VERSION"
    "$STAGE_BIN/rustbio" --version | grep -q "$RUSTBIO_VERSION"
    "$VENV_DIR/bin/python" -c "import matplotlib, pandas, pyfaidx, tabulate; assert matplotlib.__version__ == '$MATPLOTLIB_VERSION'; assert pandas.__version__ == '$PANDAS_VERSION'; assert pyfaidx.__version__ == '$PYFAIDX_VERSION'; assert tabulate.__version__ == '$TABULATE_VERSION'"
    "$TOOLS_DIR/zebrac" --version >/dev/null
}

publish() {
    local name
    mkdir -p "$BIN_DIR" "$LIB_DIR"
    for name in samtools bedtools seqkit seqtk fastahack noodles rustbio; do
        case "$name" in
            seqkit) ;;
            *) strip --strip-unneeded "$STAGE_BIN/$name" ;;
        esac
        install -m 755 "$STAGE_BIN/$name" "$BIN_DIR/$name"
    done
    cp -a "$STAGE_LIB"/libhts.so* "$LIB_DIR/"
    ln -sfn ../venv/bin/faidx "$BIN_DIR/faidx"
}

require_command curl
require_command git
require_command make
require_command cargo
require_command python3
require_command patchelf
require_command strip

build_samtools
build_bedtools
build_seqkit
build_seqtk
build_fastahack
build_wrapper noodles_wrapper noodles_wrapper noodles
build_wrapper rustbio_wrapper rustbio_wrapper rustbio
install_python_tools
verify_stage
publish

echo "Local benchmark tools installed under $TOOLS_DIR"
"$BIN_DIR/samtools" --version | awk 'NR <= 2'
"$BIN_DIR/bedtools" --version
"$BIN_DIR/seqkit" version
{ "$BIN_DIR/seqtk" 2>&1 || true; } | grep '^Version:'
"$BIN_DIR/noodles" --version
"$BIN_DIR/rustbio" --version
"$BIN_DIR/faidx" --version
